#!/bin/bash

curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
curl -X POST http://localhost:9000/api/v1/users -H "Content-Type: application/json" -d '{"email":"john@example.com","name":"John Doe","password":"secret123","role":"viewer"}'
