# https://www.playframework.com/documentation/latest/Configuration
## conf/application.conf
play {                                                                                                                                          
	http.secret.key = "changeme"
	http.secret.key = ${?APPLICATION_SECRET}
	http.filters = "filters.Filters"

	modules {
		enabled += "modules.ServiceModule"
	}
}
