# https://www.playframework.com/documentation/latest/Configuration
## conf/application.conf
play {
  http.secret.key = "changeme"
  http.secret.key = ${?APPLICATION_SECRET}

  modules {
    enabled += "modules.ServiceModule"
  }

  filters {
    enabled += "play.filters.cors.CORSFilter"
  }

  filters.cors {
    allowedOrigins = ["http://localhost:3000"]
    allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowedHttpHeaders = ["Accept", "Content-Type", "Authorization"]
  }
}
